version: '2'

services:
  blanketdb:
    image: luphord/blanketdb:latest
    command: uwsgi --socket 0.0.0.0:3031 --plugins python3 --protocol uwsgi --wsgi blanketdb_wsgi:application
    build:
      context: .
    volumes:
      - /tmp/db:/usr/src/app/db

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - blanketdb
    ports:
      - 80:80
